# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsScene, QGraphicsView, QGraphicsRectItem, QGraphicsEllipseItem, QHBoxLayout, QVBoxLayout
from PyQt6.QtGui import QPainter, QBrush, QColor
import random
from PyQt6.QtCore import Qt

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(210, 290, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Dela Gothic One")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.a = QtWidgets.QWidget(parent=Form)
        self.a.setGeometry(QtCore.QRect(130, 30, 350, 250))
        layout = QHBoxLayout()
        view = QGraphicsView(Ui_Form.draw_something(self))
        layout.addWidget(view)
        self.a.setLayout(layout)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Is this correct?"))

    def setColor(self):
        colorlist = ["Green", "Red", "Yellow", "Blue", "Black", "Pink", "Gray", "Orange", "Purple"]
        number = random.randint(0, len(colorlist) - 1)
        return colorlist[number]

    def draw_something(self):
        scene = QGraphicsScene(0, 0, 0, 0)
        finalcolors = []
        finalcolors.append(Ui_Form.setColor(self))
        finalcolors.append(Ui_Form.setColor(self))
        f = random.randint(0, 1)
        if f == 1:
            s = 0
        else:
            s = 1
        firstround = QGraphicsEllipseItem(-150, -100, 70, 70)
        br = QBrush(QColor(finalcolors[f]))
        firstround.setBrush(br)
        scene.addItem(firstround)
        secondround = QGraphicsEllipseItem(0, -100, 70, 70)
        br = QBrush(QColor(finalcolors[s]))
        secondround.setBrush(br)
        scene.addItem(secondround)
        font = QtGui.QFont()
        font.setFamily("Dela Gothic One")
        font.setPointSize(10)
        f = random.randint(0, 1)
        if f == 1:
            s = 0
        else:
            s = 1
        f2 = random.randint(0, 1)
        if f2 == 1:
            s2 = 0
        else:
            s2 = 1
        text1 = scene.addText(finalcolors[f])
        text1.setFont(font)
        text1.setPos(-142, 0)
        text1.setDefaultTextColor(QColor(finalcolors[f2]))
        text1 = scene.addText(finalcolors[s])
        text1.setFont(font)
        text1.setPos(10, 0)
        text1.setDefaultTextColor(QColor(finalcolors[s2]))
        return scene


