# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import random

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsScene, QGraphicsView, QGraphicsRectItem, QGraphicsEllipseItem, QHBoxLayout, QVBoxLayout
from PyQt6.QtGui import QPainter, QBrush, QColor


class Ui_Form2(object):
    def setupUi(self, Form):
        x = random.randint(1, 10)
        y = random.randint(1, 10)
        while x == y:
            y = random.randint(1, 10)
        if x > y:
            self.answer2 = QtWidgets.QLineEdit("R")
        else:
            self.answer2 = QtWidgets.QLineEdit("L")
        self.answer2.setVisible(False)
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(180, 270, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Dela Gothic One")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Right = QtWidgets.QPushButton(parent=Form)
        self.Right.setGeometry(QtCore.QRect(70, 320, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Dela Gothic One")
        self.Right.setFont(font)
        self.Right.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 0px solid; border-radius: 20px;")
        self.Right.setObjectName("Right")
        self.Left = QtWidgets.QPushButton(parent=Form)
        self.Left.setGeometry(QtCore.QRect(410, 320, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Dela Gothic One")
        self.Left.setFont(font)
        self.Left.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 0px solid; border-radius: 20px;\n"
"")
        self.Left.setObjectName("Left")
        self.fw = QtWidgets.QWidget(parent=Form)
        self.fw.setGeometry(QtCore.QRect(100, 55, 170, 200))
        self.sw = QtWidgets.QWidget(parent=Form)
        self.sw.setGeometry(QtCore.QRect(340, 55, 170, 200))
        layout = QHBoxLayout()
        view = QGraphicsView(Ui_Form2.draw_windows(self, x))
        layout.addWidget(view)
        layout2 = QHBoxLayout()
        view = QGraphicsView(Ui_Form2.draw_windows(self, y))
        layout2.addWidget(view)
        self.fw.setLayout(layout)
        self.sw.setLayout(layout2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Where is more?"))
        self.Right.setText(_translate("Form", "Right"))
        self.Left.setText(_translate("Form", "Left"))

    def draw_windows(self, count):
        scene = QGraphicsScene(0, 0, 0, 0)
        for i in range(count):
            firstround = QGraphicsEllipseItem(random.randint(0, 100), random.randint(0, 100), 5, 5)
            br = QBrush(QColor("Black"))
            firstround.setBrush(br)
            scene.addItem(firstround)
        return scene

