# Form implementation generated from reading ui file '4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import random

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsScene, QGraphicsView, QGraphicsRectItem, QGraphicsEllipseItem, QHBoxLayout, QVBoxLayout
from PyQt6.QtGui import QPainter, QBrush, QColor


class Ui_Form3(object):
    def setupUi(self, Form):
        x = random.randint(1, 20)
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.answer3 = QtWidgets.QLineEdit(str(x))
        self.answer3.setVisible(False)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(140, 60, 300, 200))
        self.label.setText("")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setGeometry(QtCore.QRect(130, 340, 171, 21))
        self.textEdit.setObjectName("textEdit")
        self.ans = QtWidgets.QPushButton(parent=Form)
        self.ans.setGeometry(QtCore.QRect(330, 330, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Dela Gothic One")
        self.ans.setFont(font)
        self.ans.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border: 0px solid; border-radius: 20px;")
        self.ans.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(220, 270, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Dela Gothic One")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        layout = QHBoxLayout()
        view = QGraphicsView(Ui_Form3.draw_window(self, x))
        layout.addWidget(view)
        self.label.setLayout(layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ans.setText(_translate("Form", "Answer"))
        self.label_2.setText(_translate("Form", "How much?"))

    def draw_window(self, count):
        scene = QGraphicsScene(0, 0, 0, 0)
        for i in range(count):
            firstround = QGraphicsEllipseItem(random.randint(0, 100), random.randint(0, 100), 5, 5)
            br = QBrush(QColor("Black"))
            firstround.setBrush(br)
            scene.addItem(firstround)
        return scene